Name: 'Aquaman'
Tier: 'rare'
Description:
  - 'Grants %enchantment_potion_type% %enchantment_potion_level% effect that costs x1 %enchantment_cost_item%.'
Is_Treasure: false
Level:
  Min: 1
  Max: 1
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '%enchantment_level% * 15.0'
  Chance: 25.0
Villagers:
  Chance: 25.0
Loot_Generation:
  Chance: 25.0
Settings:
  Trigger_Chance: '100.0'
  Cost:
    Enabled: true
    Item:
      material: PRISMARINE_SHARD
  Potion_Effect:
    Level: '1'
    Duration: '25.0'