Is_Treasure: false
Name: Bomber
Tier: exotic
Description:
  - '%enchantment_trigger_chance%% chance to launch TNT instead of an arrow.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 20.0
Villagers:
  Chance: 15.0
Loot_Generation:
  Chance: 15.0
Settings:
  Trigger_Chance: '0.6 * %enchantment_level%'
  Fuse_Ticks: '90 - %enchantment_level%'