Is_Treasure: false
Name: Confusion
Tier: common
Description:
  - '%enchantment_trigger_chance%% chance to apply %enchantment_potion_type% %enchantment_potion_level% for %enchantment_potion_duration%s. on hit.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 60.0
Villagers:
  Chance: 60.0
Loot_Generation:
  Chance: 60.0
Settings:
  Trigger_Chance: '15.0 * %enchantment_level%'
  Potion_Effect:
    Duration: '5.0 + %enchantment_level% * 1.5'
    Level: '%enchantment_level%'
  Particle_Effect: ITEM_CRACK:ROTTEN_FLESH
