Is_Treasure: false
Name: Flame Walker
Tier: exotic
Description:
  - 'Ability to walk on lava.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 20.0
Villagers:
  Chance: 20.0
Loot_Generation:
  Chance: 25.0
Settings:
  Trigger_Chance: '100.0'
