Is_Treasure: false
Name: Lucky Miner
Tier: common
Description:
  - '%enchantment_trigger_chance%% chance to obtain +%exp%% more exp from ores.'
Level:
  Min: 1
  Max: 5
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '5 * %enchantment_level%'
  Chance: 50.0
Villagers:
  Chance: 50.0
Loot_Generation:
  Chance: 50.0
Settings:
  Trigger_Chance: '50.0 + %enchantment_level% * 5'
  Exp_Modifier: '1.5 + %enchantment_level% / 10'
