Is_Treasure: false
Name: Paralyze
Tier: legendary
Description:
  - '%enchantment_trigger_chance%% chance to apply %enchantment_potion_type% %enchantment_potion_level% for %enchantment_potion_duration%s. on hit.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 10.0
Villagers:
  Chance: 10.0
Loot_Generation:
  Chance: 10.0
Settings:
  Trigger_Chance: '5.0 + %enchantment_level% * 1.5'
  Potion_Effect:
    Duration: '2.5 + %enchantment_level%'
    Level: '5'
  Particle_Effect: 'CRIT_MAGIC'
