Is_Treasure: false
Name: Self-Destruction
Tier: exotic
Description:
  - '%enchantment_trigger_chance%% chance to create an x%power% power explosion on death.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 50.0
Villagers:
  Chance: 50.0
Loot_Generation:
  Chance: 50.0
Settings:
  Trigger_Chance: '20.0 + %enchantment_level% * 10'
  Explosion:
    Size: '1.0 + %enchantment_level%'
