Is_Treasure: false
Name: Sonic
Tier: rare
Description:
  - 'Grants %enchantment_potion_type% %enchantment_potion_level% effect that costs x1 %enchantment_cost_item%.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 30.0
Villagers:
  Chance: 40.0
Loot_Generation:
  Chance: 40.0
Settings:
  Trigger_Chance: '100.0'
  Cost:
    Enabled: true
    Item:
      material: FEATHER
  Potion_Effect:
    Duration: '25.0'
    Level: '%enchantment_level%'
