Is_Treasure: false
Name: Surprise
Tier: exotic
Description:
  - '%enchantment_trigger_chance%% chance to apply random potion effect to enemy on hit.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 35.0
Villagers:
  Chance: 35.0
Loot_Generation:
  Chance: 35.0
Settings:
  Trigger_Chance: 2.25 * %enchantment_level%
  Potion_Effect:
    Duration: '3.0 + %enchantment_level%'
    Level: '%enchantment_level%'
