Is_Treasure: false
Name: Telekinesis
Tier: exotic
Description:
  - 'Moves all blocks loot directly to your inventory.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 30.0
Villagers:
  Chance: 30.0
Loot_Generation:
  Chance: 30.0
Settings:
  Trigger_Chance: '100.0'
  Message:
    Drop_Received: '{message: ~type: ACTION_BAR; ~prefix: false;}%items%'
    Item_Name: '&7x%item_amount% &f%item_name%'
    Item_Separator: '&7, '
