Is_Treasure: false
Name: Veinminer
Tier: rare
Description:
  - 'Mines up to %blocks_amount% blocks of ore vein at once.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 20.0
Villagers:
  Chance: 10.0
Loot_Generation:
  Chance: 10.0
Settings:
  Trigger_Chance: '100.0'
  Blocks:
    Max_At_Once: '6 + %enchantment_level%'
    Affected:
      - COAL_ORE
      - GOLD_ORE
      - IRON_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
      - COPPER_ORE
      - DEEPSLATE_COAL_ORE
      - DEEPSLATE_GOLD_ORE
      - DEEPSLATE_IRON_ORE
      - DEEPSLATE_DIAMOND_ORE
      - DEEPSLATE_EMERALD_ORE
      - DEEPSLATE_LAPIS_ORE
      - DEEPSLATE_REDSTONE_ORE
      - DEEPSLATE_COPPER_ORE
      - NETHER_QUARTZ_ORE
      - NETHER_GOLD_ORE