Is_Treasure: false
Name: Venom
Tier: rare
Description:
  - '%enchantment_trigger_chance%% chance to apply %enchantment_potion_type% %enchantment_potion_level% for %enchantment_potion_duration%s. on hit.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 50.0
Villagers:
  Chance: 55.0
Loot_Generation:
  Chance: 55.0
Settings:
  Trigger_Chance: '30.0 + %enchantment_level% * 10.0'
  Potion_Effect:
    Duration: '2.0 + %enchantment_level%'
    Level: '%enchantment_level%'
  Particle_Effect: SLIME
