Is_Treasure: false
Name: Wither
Tier: rare
Description:
  - '%enchantment_trigger_chance%% chance to apply %enchantment_potion_type% %enchantment_potion_level% for %enchantment_potion_duration%s. on hit.'
Level:
  Min: 1
  Max: 3
Anvil:
  Merge_Cost: '%enchantment_level%'
Enchantment_Table:
  Level_By_Exp_Cost: '9 * %enchantment_level%'
  Chance: 30.0
Villagers:
  Chance: 30.0
Loot_Generation:
  Chance: 30.0
Settings:
  Trigger_Chance: '15.0 + %enchantment_level% * 7.5'
  Potion_Effect:
    Duration: '3.0 + %enchantment_level%'
    Level: '%enchantment_level%'
  Particle_Effect: SPELL_WITCH
