name: antiRedstoneClock
version: 1.5.0
description: Limit the redstoneClock
author: Amosar
website: https://www.spigotmc.org/resources/antiredstoneclock.18557
api-version: 1.13
softdepend: [WorldGuard, bstats, PlotSquared]

main: com.trafalcraft.anti_redstone_clock.Main

commands:
   antiRedstoneClock:
     description: Base command for the antiRedstoneClock plugin.
     aliases: [arc]
